### ISSUE TITLE
Custom updater for amcrest

### ISSUE THREAD

**Issue by danobot** [pnbruckner/homeassistant-config#109]
Hi Phil,
Can you please add this file to `custom_component/amcrest` to allow people to receive automatic updates while this is in development?

Just bump the version for the changed file when required. You can use a simple integer if you dont want to use SemVer.

**tracker.json**
```yaml
{
    "amcrest_component_init": {
      "version": "0.1.0",
      "local_location": "/custom_components/amcrest/__init__.py",
      "remote_location": "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/amcrest-update/custom_components/amcrest/__init__.py",
      "visit_repo": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components",
      "changelog": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components"
    },
    "amcrest_component_binary_sensor": {
      "version": "0.1.0",
      "local_location": "/custom_components/amcrest/binary_sensor.py",
      "remote_location": "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/amcrest-update/custom_components/amcrest/binary_sensor.py",
      "visit_repo": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components",
      "changelog": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components"
    },
    "amcrest_component_camera": {
      "version": "0.1.0",
      "local_location": "/custom_components/amcrest/camera.py",
      "remote_location": "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/amcrest-update/custom_components/amcrest/camera.py",
      "visit_repo": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components",
      "changelog": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components"
    },
    "amcrest_component_sensor": {
      "version": "0.1.0",
      "local_location": "/custom_components/amcrest/sensor.py",
      "remote_location": "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/amcrest-update/custom_components/amcrest/sensor.py",
      "visit_repo": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components",
      "changelog": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components"
    },
    "amcrest_component_switch": {
      "version": "0.1.0",
      "local_location": "/custom_components/amcrest/switch.py",
      "remote_location": "https://raw.githubusercontent.com/pnbruckner/homeassistant-config/amcrest-update/custom_components/amcrest/switch.py",
      "visit_repo": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components",
      "changelog": "https://github.com/pnbruckner/homeassistant-config/tree/amcrest-update/custom_components"
    }
}

```
