### ISSUE TITLE
Config error check

### ISSUE THREAD

**Issue by jerrybarnett** [pnbruckner/homeassistant-config#115]
Receiving the following for Life360 (v2.8.0) after initial installation when doing a configuration check:
Invalid config for [device_tracker.life360]: offset None should be format 'HH:MM' or 'HH:MM:SS' for dictionary value @ data['max_update_wait']. Got None. (See ?, line ?). 

Device_tracker.py is under folder <config>/custom_components/life360.  And I even placed a blank __init__.py file there as well.  
Configuration.yaml has:
```
device_tracker:
  - platform: life360
    username: !secret life360_user
    password: !secret life360_pass
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    time_as: device_or_local
    max_update_wait:
    minutes: 45
```

Any suggestions on what I may have missed?  HA version is latest at v 0.89.2
