### ISSUE TITLE
Life360 not showing in Custom_Updater

### ISSUE THREAD

**Issue by MightyMilster** [pnbruckner/homeassistant-config#137]
Hi. My existing setup for custom updater just detected v2.9.3, so I hit Update All. The update was done but now Life360 has vanished from my list of Custom Components. I went to this resource and saw the requirement for `__init__.py` and `manifest.json` (which I didn't have before now). I've added those now (yes, via the raw version) but still no joy getting Life360 to appear in my list. Do I need a `component_urls:` reference in my `custom_updater:` setup in `configuration.yaml` - I got the impression this wasn't required. I'm running hass.io v0.91.4 and Custom_Updater is v4.2.19. Any ideas?

**Comment by MightyMilster** [comment]
Ah well. I suppose I did require some additional setup. Added this in my `configuration.yaml` and she's back!
```
custom_updater:
  show_installable: false
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json
```
