### ISSUE TITLE
device tracker was not updating timely

### ISSUE THREAD

**Issue by shreram** [pnbruckner/homeassistant-config#45]
For some reason since the last update (1.5.0), device_tracker entities were not updated quickly. In some cases status was not updated for more than an hour. 

I added automations to test entities based on their speed but they were not triggered at all.

My config file entries:

```
device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 8
    max_update_wait:
      minutes: 15
    interval_seconds: 10
    filename: life360.conf
```
I commented out _max_update_wait_ settings but still the same. Are there any settings that were needed to be adjusted?

TIA
