### ISSUE TITLE
Life360: inconsistent last_seen updates

### ISSUE THREAD

**Issue by shreram** [pnbruckner/homeassistant-config#78]
I have the following template to track 'last_seen' but that value is inconsistent. I am not sure if this was because of Life360 or issue with the template.

```
      tmpl_aaa_loc_updated_at:
        friendly_name: A's Location Changed At
        value_template: "{{relative_time(states.device_tracker.life360_aaa.attributes.last_seen)}}"
        entity_id: device_tracker.life360_aaa
```

8:14 PM A's Location Changed At changed to 12 months
8:08 PM A changed to Driving
7:48 PM A changed to location 2
7:47 PM A's Location Changed At changed to 12 months
7:43 PM A changed to location 1
7:41 PM A's Location Changed At changed to 3 seconds
7:28 PM A changed to Moving
